language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t musthafakdml/test-client-app -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true musthafakdml/test-client-app npm run test -- --coverage

after_success:
    - docker build -t musthafakdml/complex-app-client ./client
    - docker build -t musthafakdml/complex-app-nginx ./nginx
    - docker build -t musthafakdml/complex-app-worker ./worker
    - docker build -t musthafakdml/complex-app-server ./server
    # Login to docker to push the images to the docker-hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push musthafakdml/complex-app-client
    - docker push musthafakdml/complex-app-nginx
    - docker push musthafakdml/complex-app-worker
    - docker push musthafakdml/complex-app-server